### ISSUE TITLE
Heroku purge_cache error

### ISSUE THREAD

**Issue by RianaFerreira** [heroku/heroku-repo#42] opened 2015-09-30 07:08 UTC
I get the below error when attempting to purge the cache on my Heroku staging app.
Has anyone else reported this? The command was working for me until today. 
Any help would be appreciated, thanks!

CLI output:
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `index' for #<Heroku::Command::Run:0x000001009777b8> (NoMethodError)
    Command:     heroku repo:purge_cache --app taupo-staging
    Plugins:     heroku-repo
    Version:     heroku-toolbelt/3.42.12 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    ccf448694c4140a994834a0da7877703

Log output:
Heroku client internal error.
undefined method `index' for #<Heroku::Command::Run:0x00000101463618>
/Users/riana/.heroku/plugins/heroku-repo/lib/heroku/command/repo.rb:139:in `run'
/Users/riana/.heroku/plugins/heroku-repo/lib/heroku/command/repo.rb:37:in `purge_cache'
/Users/riana/.heroku/client/lib/heroku/command.rb:212:in `run'
/Users/riana/.heroku/client/lib/heroku/cli.rb:29:in `start'
/usr/bin/heroku:24:in `<main>'
2015/09/30 16:53:23 running from /Users/riana/.heroku/heroku-cli

**Comment by tt** [comment] 2015-09-30 12:37
This looks like a duplicate of #14.

Can you try updating the plug-in (i.e. `heroku plugins:update`) and reopen if that doesn't resolve it?

**Closed by tt** 2015-09-30 12:37 UTC

**Comment by RianaFerreira** [comment] 2015-09-30 22:01
Magical! Thank you very much :+1:
